### ISSUE TITLE
SlackAlert::shouldReceive('message'); throw error when using SlackAlert:to()

### ISSUE THREAD

**Issue by jwhulette** [spatie/laravel-slack-alerts#43]
Using this test
```
it("can dispatch a job to send a message to slack using to and alternate webhook url", function () {
    config()->set('slack-alerts.webhook_urls.other', 'https://test-domain.com');

    SlackAlert::shouldReceive('message');

    SlackAlert::to('other')->message('test-data');
});
```

Throws the error
```

   Mockery\Exception\BadMethodCallException 

  Received Mockery_0_Spatie_SlackAlerts_SlackAlert::to(), but no expectations were specified

  at vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355
    351▕         if (! $instance) {
    352▕             throw new RuntimeException('A facade root has not been set.');
    353▕         }
    354▕ 
  ➜ 355▕         return $instance->$method(...$args);
    356▕     }
    357▕ }
    358▕ 

  1   tests/SlackAlertsTest.php:18
```

**Comment by freekmurze** [comment]
Seems like all our tests are currently passing, both locally and on GitHub Actions
https://github.com/spatie/laravel-slack-alerts/actions/runs/7032160684

**Comment by jwhulette** [comment]
@freekmurze It does pass with your current tests, but if you add the test I provided and run the tests if fails. Specifically if you use the to method and the SlackAlert::shouldReceive('message'); testing helper.

**Comment by jwhulette** [comment]
If someone comes across this, you can do:

SlackAlert::shouldReceive('to', 'message')->once()->andReturnSelf();

**Comment by Slund** [comment]
> If someone comes across this, you can do:
> 
> SlackAlert::shouldReceive('to', 'message')->once()->andReturnSelf();

Thanks! Exactly what I needed.
