### ISSUE TITLE
"The script tried to call a method on an incomplete object"

### ISSUE THREAD

**Issue by MrMooky** [spatie/laravel-slack-alerts#8]
When calling `SlackAlert::message("New signup on FeatureShift: {$user->email} :tada:");` I get the following error:

> [2022-02-19 15:29:33] production.ERROR: The script tried to call a method on an incomplete object. Please ensure that the class definition "Spatie\SlackAlerts\Jobs\SendToSlackChannelJob" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition {"exception":"[object] (Error(code: 0): The script tried to call a method on an incomplete object. Please ensure that the class definition \"Spatie\\SlackAlerts\\Jobs\\SendToSlackChannelJob\" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition at /home/xxxxx/webapps/xxxxx/releases/20220219141754/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:295)

Am I missing something? Setup seemed pretty straightforward.

**Comment by MrMooky** [comment]
Was an issue on my end.

**Comment by fdabek1** [comment]
> Was an issue on my end.

What was the issue?!?  I'm having the same issue and can't figure out what I'm missing.
